package proje.proje_2;
import java.util.ArrayList;
import javax.swing.JLabel;
public class GameScreen extends javax.swing.JFrame {

Oyuncu oyuncu=new Oyuncu();
Test test=new Test();

Futbolcu[] FkartListesi=new Futbolcu[8];
Basketbolcu[] BkartListesi=new Basketbolcu[8];
int[] futbolAt=new int[8];
int[] basketbolAt=new int[8];
int[] pozAt=new int[3];
int[] labelAt=new int[4];
boolean Bkontrol=false,Fkontrol=true;
int labelKont=0,sıra=0,secKartKont;
JLabel[] PCkartlari=new JLabel[8];
int kartKont=0;
int oyuncuSkor=0;
int bilgisayarSkor=0;
boolean ButonKontrol=true;
int futbol;
int basketbol;
String poz;
int pozisyon;


    public void kartıAl(Futbolcu[] fdizi,Basketbolcu[] bdizi){
        
    FkartListesi=fdizi;
    BkartListesi=bdizi;
    }
    public void futbolAttır(int[] dizi){
    futbolAt=dizi;
    }
    public void basketbolAttır(int[] dizi){
    basketbolAt=dizi ;
    }
    
    public void pozAttır(int[] dizi){
    pozAt=dizi;
    }
    public void labelAttır(int[] dizi){
    labelAt=dizi;
    }

    public GameScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1270, 50, 160, 210);

        jButton2.setText("Kartı Seç");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1300, 330, 120, 50);

        jButton1.setText("Sonraki Tur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1300, 420, 120, 50);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg")); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(50, 550, 142, 200);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(200, 550, 142, 200);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg")); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(350, 550, 142, 200);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg")); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(500, 550, 142, 200);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg")); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(650, 550, 142, 200);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg")); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(800, 550, 142, 200);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(950, 550, 142, 200);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1100, 550, 142, 200);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1100, 50, 142, 200);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(950, 50, 142, 200);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(800, 50, 142, 200);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 50, 142, 200);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 50, 142, 200);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 50, 142, 200);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 50, 142, 200);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 50, 142, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\gameBackground.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 800);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1538, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1538, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void kartlarıDagıt(){
    jLabel10.setIcon(new javax.swing.ImageIcon(BkartListesi[basketbolAt[0]].getSporcuKartYolu()));
    jLabel11.setIcon(new javax.swing.ImageIcon(BkartListesi[basketbolAt[1]].getSporcuKartYolu()));
    jLabel12.setIcon(new javax.swing.ImageIcon(BkartListesi[basketbolAt[2]].getSporcuKartYolu()));
    jLabel13.setIcon(new javax.swing.ImageIcon(BkartListesi[basketbolAt[3]].getSporcuKartYolu())); 
    jLabel14.setIcon(new javax.swing.ImageIcon(FkartListesi[futbolAt[4]].getSporcuKartYolu()));
    jLabel15.setIcon(new javax.swing.ImageIcon(FkartListesi[futbolAt[5]].getSporcuKartYolu())); 
    jLabel16.setIcon(new javax.swing.ImageIcon(FkartListesi[futbolAt[6]].getSporcuKartYolu())); 
    jLabel17.setIcon(new javax.swing.ImageIcon(FkartListesi[futbolAt[7]].getSporcuKartYolu()));
    PCkartlari[0]=jLabel2;
    PCkartlari[1]=jLabel3;
    PCkartlari[2]=jLabel4;
    PCkartlari[3]=jLabel5;
    PCkartlari[4]=jLabel6;
    PCkartlari[5]=jLabel7;
    PCkartlari[6]=jLabel8;
    PCkartlari[7]=jLabel9;
    }

    
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
            if (Bkontrol==true) {
            Fkontrol=false;
            Bkontrol=false;
            jLabel10.setLocation(500, 300);
            kartKont=10;
            sıra++;
            BkartListesi[basketbolAt[0]].setKartKullanildiMi(true);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
            if (Bkontrol==true) {
            Fkontrol=false;
            Bkontrol=false;
            jLabel11.setLocation(500, 300);
            kartKont=11;
            sıra++;
            BkartListesi[basketbolAt[1]].setKartKullanildiMi(true);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if (Bkontrol==true) {
            Fkontrol=false;
            Bkontrol=false;
            jLabel12.setLocation(500, 300);
            kartKont=12;
            sıra++;
            BkartListesi[basketbolAt[2]].setKartKullanildiMi(true);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
            if (Bkontrol==true) {
            Fkontrol=false;
            Bkontrol=false;
            jLabel13.setLocation(500, 300);
            kartKont=13;
            sıra++;
            BkartListesi[basketbolAt[3]].setKartKullanildiMi(true);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if (Fkontrol==true) {
            Fkontrol=false;
            Bkontrol=false;
            jLabel14.setLocation(500, 300);
            kartKont=14;
            sıra++;
            FkartListesi[futbolAt[4]].setKartKullanildiMi(true);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if (Fkontrol==true) {
        Fkontrol=false;
        Bkontrol=false;
        jLabel15.setLocation(500, 300);     
        kartKont=15;
        sıra++;
        FkartListesi[futbolAt[5]].setKartKullanildiMi(true);
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        if (Fkontrol==true) {
        Fkontrol=false;
        Bkontrol=false;
        jLabel16.setLocation(500, 300); 
        kartKont=16;
        sıra++;
        FkartListesi[futbolAt[6]].setKartKullanildiMi(true);
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        if (Fkontrol==true) {
            Fkontrol=false;
            Bkontrol=false;
            jLabel17.setLocation(500, 300); 
            kartKont=17;
            secKartKont=futbolAt[7];
            sıra++;
            FkartListesi[futbolAt[7]].setKartKullanildiMi(true);
        }

    }//GEN-LAST:event_jLabel17MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       if(sıra%2==1){
       PCkartlari[futbol].setVisible(false);
       Bkontrol=true;}
       else if(sıra%2==0){
       PCkartlari[basketbol].setVisible(false);
       Fkontrol=true;}
       
    switch (kartKont) {
        case 17:
            jLabel17.setVisible(false);break;
        case 16:
            jLabel16.setVisible(false);break;
        case 15:
            jLabel15.setVisible(false);break;
        case 14:
            jLabel14.setVisible(false);break;
        case 13:
            jLabel13.setVisible(false);break;
        case 12:
            jLabel12.setVisible(false);break;
        case 11:
            jLabel11.setVisible(false);break;
        case 10:
            jLabel10.setVisible(false);break;
        default:break;
    }
       
        if(labelKont>4)
            jTextPane1.setText(oyuncu.skorGoster(oyuncuSkor, bilgisayarSkor));
  
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(sıra%2==1){
    PCkartlari[labelAt[labelKont]].setLocation(650,300);
    PCkartlari[labelAt[labelKont]].setIcon(new javax.swing.ImageIcon(FkartListesi[futbolAt[labelKont]].getSporcuKartYolu())); 
    FkartListesi[futbolAt[labelKont]].setKartKullanildiMi(true);
    futbol=labelAt[labelKont];
    pozisyon =(int) (Math.random() * 3);
    
        switch (pozisyon) {
            case 0:
                poz="Penalti";
                break;
            case 1:
                poz="Serbest Vurus";
                break;
            default:
                poz="Kaleciyle Karsi Karsiya";
                break;
        }
        
        switch (karsilastirFutbolcu(futbolAt[labelKont],futbolAt[kartKont%10],pozisyon)) {
            case 1:
                jTextPane1.setText("Pozisyon:"+poz+"\n5 Puan Kazandınız...");
                oyuncuSkor=oyuncuSkor+5;
                break;
            case 0:
                jTextPane1.setText("Pozisyon:"+poz+"\nBerabere.Kimse Puan Alamadı...\nLütfen yeniden kart seçiniz");
                berabereDurumu(futbol);
                berabereDurumu(kartKont);
                Fkontrol=true;Bkontrol=false;
                labelKont--;sıra--;
                break;
            case -1:
                jTextPane1.setText("Pozisyon:"+poz+"\nBilgisayar 5 Puan Kazandı...");
                bilgisayarSkor=bilgisayarSkor+5;
                break;
            default:
                break;
        }
    labelKont++;
    }
    else{
    PCkartlari[labelAt[labelKont-1]+4].setLocation(650,300);
    PCkartlari[labelAt[labelKont-1]+4].setIcon(new javax.swing.ImageIcon(BkartListesi[basketbolAt[labelKont+3]].getSporcuKartYolu()));
    BkartListesi[basketbolAt[labelKont+3]].setKartKullanildiMi(true);
    basketbol= labelAt[labelKont-1]+4;
    pozisyon =(int) (Math.random() * 3);
    
        switch (pozisyon) {
            case 0:
                poz="Ucluk";
                break;
            case 1:
                poz="Ikilik";
                break;
            default:
                poz="Serbset Atis";
                break;
        }

        switch (karsilastirBasketbolcu(basketbolAt[labelKont+3],basketbolAt[kartKont%10],pozisyon)) {
            case 1:
                jTextPane1.setText("Pozisyon:"+poz+"\n5 Puan Kazandınız...");
                oyuncuSkor=oyuncuSkor+5;
                break;
            case 0:
                jTextPane1.setText("Pozisyon:"+poz+"\nBerabere.Kimse Puan Alamadı...\nLütfen yeniden kart seçiniz");
                berabereDurumu(basketbol);
                berabereDurumu(kartKont);
                Fkontrol=false;Bkontrol=true;
                labelKont--;sıra--;
                break;
            case -1:
                jTextPane1.setText("Pozisyon:"+poz+"\nBilgisayar 5 Puan Kazandı...");
                bilgisayarSkor=bilgisayarSkor+5;
                break;
            default:
                break;
        }
    if(labelKont==4)
        labelKont++;
    }
    }//GEN-LAST:event_jButton2ActionPerformed
    public int karsilastirFutbolcu(int BkartListIndex,int KkartListIndex,int pozisyon){
    switch (pozisyon) {
        case 0:
            if(FkartListesi[KkartListIndex].getPenalti()>FkartListesi[BkartListIndex].getPenalti())
                return 1;
            else if(FkartListesi[KkartListIndex].getPenalti()==FkartListesi[BkartListIndex].getPenalti())
                return 0;
            else
                return -1;
        case 1:
            if(FkartListesi[KkartListIndex].getSetbestVurus()>FkartListesi[BkartListIndex].getSetbestVurus())
                return 1;
            else if(FkartListesi[KkartListIndex].getSetbestVurus()==FkartListesi[BkartListIndex].getSetbestVurus())
                return 0;
            else
                return -1;
        default:
            if(FkartListesi[KkartListIndex].getKaleciKarsiKarsiya()>FkartListesi[BkartListIndex].getKaleciKarsiKarsiya())
                return 1;
            else if(FkartListesi[KkartListIndex].getKaleciKarsiKarsiya()==FkartListesi[BkartListIndex].getKaleciKarsiKarsiya())
                return 0;
            else
                return -1;
    }
    }
    public int karsilastirBasketbolcu(int BkartListIndex,int KkartListIndex,int pozisyon){
    switch (pozisyon) {
        case 0:
            if(BkartListesi[KkartListIndex].getUcluk()>BkartListesi[BkartListIndex].getUcluk())
                return 1;
            else if(BkartListesi[KkartListIndex].getUcluk()==BkartListesi[BkartListIndex].getUcluk())
                return 0;
            else
                return -1;
        case 1:
            if(BkartListesi[KkartListIndex].getIkilik()>BkartListesi[BkartListIndex].getIkilik())
                return 1;
            else if(BkartListesi[KkartListIndex].getIkilik()==BkartListesi[BkartListIndex].getIkilik())
                return 0;
            else
                return -1;
        default:
            if(BkartListesi[KkartListIndex].getSerbestAtis()>BkartListesi[BkartListIndex].getSerbestAtis())
                return 1;
            else if(BkartListesi[KkartListIndex].getSerbestAtis()==BkartListesi[BkartListIndex].getSerbestAtis())
                return 0;
            else
                return -1;
    }
    }
       public void berabereDurumu(int index){
    switch (index){
        case 0:
            jLabel2.setLocation(50, 50);
            jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg"));break;
        case 1:
            jLabel3.setLocation(200, 50);
            jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg"));break;
        case 2:
            jLabel4.setLocation(350, 50);
            jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg"));break;
        case 3:
            jLabel5.setLocation(500, 50);
            jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\fkartarka.jpg"));break;
        case 4:
            jLabel6.setLocation(650, 50);
            jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg"));break;
        case 5:
            jLabel7.setLocation(800, 50);
            jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg"));break;
        case 6:
            jLabel8.setLocation(950, 50);
            jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg"));break;
        case 7:
            jLabel9.setLocation(1100, 50);
            jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\yavuz\\Desktop\\NetBeansProjects\\Proje_2\\src\\main\\java\\proje\\proje_2\\photos\\bkartarka.jpg"));break; 
        case 10:
            jLabel10.setLocation(1100, 550);break;
        case 11:
            jLabel11.setLocation(950, 550);break;
        case 12:
            jLabel12.setLocation(800, 550);break;
        case 13:
            jLabel13.setLocation(650, 550);break;
        case 14:
            jLabel14.setLocation(500, 550);break;
        case 15:
            jLabel15.setLocation(350, 550);break;
        case 16:
            jLabel16.setLocation(200, 550);break;
        case 17:
            jLabel17.setLocation(50, 550);break;
            default:break;
    }
    }
    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public Futbolcu[] getFkartListesi() {
        return FkartListesi;
    }

    public void setFkartListesi(Futbolcu[] FkartListesi) {
        this.FkartListesi = FkartListesi;
    }

    public Basketbolcu[] getBkartListesi() {
        return BkartListesi;
    }

    public void setBkartListesi(Basketbolcu[] BkartListesi) {
        this.BkartListesi = BkartListesi;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
